AWSTemplateFormatVersion: 2010-09-09

Parameters:
  AdminPassword:
    NoEcho: true
    Description: ActiveDirectory用のパスワードです。適当なパスワードを入力してください。
    Type: String

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: Cloudformation Workspaces Vpc
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select
        - 0
        - 'Fn::GetAZs': !Ref 'AWS::Region'
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Public Subnet 1 for CloudFormation WorkSpaces
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select
        - 1
        - 'Fn::GetAZs': !Ref 'AWS::Region'
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Public Subnet 2 for CloudFormation WorkSpaces
  SimpleAD:
    Type: AWS::DirectoryService::SimpleAD
    Properties:
      Name: cloudformation.workspaces.test
      Password: !Ref AdminPassword
      Size: Small
      VpcSettings:
        SubnetIds:
          - !Ref PublicSubnet1
          - !Ref PublicSubnet2
        VpcId: !Ref VPC
